package com.sobra.shared.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    INGREDIENT_NOT_FOUND,
    FOOD_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    STALE_VERSION,
    INSUFFICIENT_QUANTITY,
    FOOD_ARCHIVED,
    LISTING_NOT_AVAILABLE,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_ACTIVE,
    LISTING_NOT_FOUND,
    IDEMPOTENCY_CONFLICT,
    USER_NOT_FOUND,
    INTERNAL_ERROR
}
