spring:
  application:
    name: sobra-backend
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: ${SOBRA_DB_URL}
    username: ${SOBRA_DB_USER}
    password: ${SOBRA_DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: false
      show-components: never
      show-details: never

sobra:
  business-zone: ${SOBRA_BUSINESS_ZONE:America/Mexico_City}

  demo-data:
    enabled: true
